# Generated by Django 5.2.7 on 2026-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='academic_level',
            field=models.CharField(choices=[('CLASS_1', 'Class 1'), ('CLASS_2', 'Class 2'), ('CLASS_3', 'Class 3'), ('CLASS_4', 'Class 4'), ('CLASS_5', 'Class 5'), ('CLASS_6', 'Class 6'), ('CLASS_7', 'Class 7'), ('CLASS_8', 'Class 8'), ('FORM_1', 'Form 1'), ('FORM_2', 'Form 2'), ('FORM_3', 'Form 3'), ('FORM_4', 'Form 4')], default='CLASS_1', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('CLASS_1', 'Class 1'), ('CLASS_2', 'Class 2'), ('CLASS_3', 'Class 3'), ('CLASS_4', 'Class 4'), ('CLASS_5', 'Class 5'), ('CLASS_6', 'Class 6'), ('CLASS_7', 'Class 7'), ('CLASS_8', 'Class 8'), ('FORM_1', 'Form 1'), ('FORM_2', 'Form 2'), ('FORM_3', 'Form 3'), ('FORM_4', 'Form 4')], help_text='Class or form assigned to the user', max_length=7, null=True),
        ),
    ]
