# Generated by Django 5.2.7 on 2026-09-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learningmaterial_academic_level_user_academic_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('academic_level', models.CharField(choices=[('CLASS_1', 'Class 1'), ('CLASS_2', 'Class 2'), ('CLASS_3', 'Class 3'), ('CLASS_4', 'Class 4'), ('CLASS_5', 'Class 5'), ('CLASS_6', 'Class 6'), ('CLASS_7', 'Class 7'), ('CLASS_8', 'Class 8'), ('FORM_1', 'Form 1'), ('FORM_2', 'Form 2'), ('FORM_3', 'Form 3'), ('FORM_4', 'Form 4')], max_length=7)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.chapter'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.chapter'),
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_chapter_order'),
        ),
        migrations.AddConstraint(
            model_name='chapterprogress',
            constraint=models.UniqueConstraint(fields=('student', 'chapter'), name='unique_student_chapter_progress'),
        ),
    ]
