# Generated by Django 5.2.7 on 2026-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chapter_learningmaterial_chapter_quiz_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate_course_levels(apps),
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_timed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='academic_level',
        ),
    ]


def populate_course_levels(apps):
    Course = apps.get_model('core', 'Course')
    LearningMaterial = apps.get_model('core', 'LearningMaterial')
    Chapter = apps.get_model('core', 'Chapter')
    for course in Course.objects.all():
        levels = set(LearningMaterial.objects.filter(course_id=course.id).values_list('academic_level', flat=True))
        levels.update(Chapter.objects.filter(course_id=course.id).values_list('academic_level', flat=True))
        course.academic_levels = sorted(level for level in levels if level)
        course.save(update_fields=['academic_levels'])
