# Generated by Django 5.2.17 on 2026-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_document_quiz_questions_and_grading"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of times a student may submit this quiz. Blank means unlimited.",
                null=True,
            ),
        ),
    ]
