# Generated by Django 5.2.17 on 2026-10-04 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_quiz_max_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"role": "INSTRUCTOR"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
